version: "3.8"

services:
  # Ứng dụng Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-cached-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      # Bind mount source code để hot reload khi development
      - .:/app
      # Exclude node_modules để tránh conflict
      - /app/node_modules
    depends_on:
      redis:
        condition: service_healthy
    restart: on-failure:5
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s
    restart: unless-stopped
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
