version: "3.8"

services:
  # Ứng dụng Node.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:9gRRLevfjQ.5piY@db.engojnukcsllexihvklf.supabase.co:5432/postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      # - db

  # Redis service
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  # # PostgreSQL service (nếu cần)
  # db:
  #   image: postgres:15-alpine
  #   container_name: postgres_db
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: pass
  #     POSTGRES_DB: mydb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  redis_data:
  # postgres_data:
